/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as HeritageRouteImport } from './routes/heritage'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ArtisansRouteImport } from './routes/artisans'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SculptureIdRouteImport } from './routes/sculpture.$id'
import { Route as HeritageIdRouteImport } from './routes/heritage.$id'
import { Route as ArtisansIdRouteImport } from './routes/artisans.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const HeritageRoute = HeritageRouteImport.update({
  id: '/heritage',
  path: '/heritage',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisansRoute = ArtisansRouteImport.update({
  id: '/artisans',
  path: '/artisans',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SculptureIdRoute = SculptureIdRouteImport.update({
  id: '/sculpture/$id',
  path: '/sculpture/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HeritageIdRoute = HeritageIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HeritageRoute,
} as any)
const ArtisansIdRoute = ArtisansIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ArtisansRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artisans': typeof ArtisansRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/heritage': typeof HeritageRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/artisans/$id': typeof ArtisansIdRoute
  '/heritage/$id': typeof HeritageIdRoute
  '/sculpture/$id': typeof SculptureIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artisans': typeof ArtisansRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/heritage': typeof HeritageRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/artisans/$id': typeof ArtisansIdRoute
  '/heritage/$id': typeof HeritageIdRoute
  '/sculpture/$id': typeof SculptureIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artisans': typeof ArtisansRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/heritage': typeof HeritageRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/artisans/$id': typeof ArtisansIdRoute
  '/heritage/$id': typeof HeritageIdRoute
  '/sculpture/$id': typeof SculptureIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artisans'
    | '/gallery'
    | '/heritage'
    | '/sitemap.xml'
    | '/artisans/$id'
    | '/heritage/$id'
    | '/sculpture/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artisans'
    | '/gallery'
    | '/heritage'
    | '/sitemap.xml'
    | '/artisans/$id'
    | '/heritage/$id'
    | '/sculpture/$id'
  id:
    | '__root__'
    | '/'
    | '/artisans'
    | '/gallery'
    | '/heritage'
    | '/sitemap.xml'
    | '/artisans/$id'
    | '/heritage/$id'
    | '/sculpture/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtisansRoute: typeof ArtisansRouteWithChildren
  GalleryRoute: typeof GalleryRoute
  HeritageRoute: typeof HeritageRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SculptureIdRoute: typeof SculptureIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heritage': {
      id: '/heritage'
      path: '/heritage'
      fullPath: '/heritage'
      preLoaderRoute: typeof HeritageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisans': {
      id: '/artisans'
      path: '/artisans'
      fullPath: '/artisans'
      preLoaderRoute: typeof ArtisansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sculpture/$id': {
      id: '/sculpture/$id'
      path: '/sculpture/$id'
      fullPath: '/sculpture/$id'
      preLoaderRoute: typeof SculptureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heritage/$id': {
      id: '/heritage/$id'
      path: '/$id'
      fullPath: '/heritage/$id'
      preLoaderRoute: typeof HeritageIdRouteImport
      parentRoute: typeof HeritageRoute
    }
    '/artisans/$id': {
      id: '/artisans/$id'
      path: '/$id'
      fullPath: '/artisans/$id'
      preLoaderRoute: typeof ArtisansIdRouteImport
      parentRoute: typeof ArtisansRoute
    }
  }
}

interface ArtisansRouteChildren {
  ArtisansIdRoute: typeof ArtisansIdRoute
}

const ArtisansRouteChildren: ArtisansRouteChildren = {
  ArtisansIdRoute: ArtisansIdRoute,
}

const ArtisansRouteWithChildren = ArtisansRoute._addFileChildren(
  ArtisansRouteChildren,
)

interface HeritageRouteChildren {
  HeritageIdRoute: typeof HeritageIdRoute
}

const HeritageRouteChildren: HeritageRouteChildren = {
  HeritageIdRoute: HeritageIdRoute,
}

const HeritageRouteWithChildren = HeritageRoute._addFileChildren(
  HeritageRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtisansRoute: ArtisansRouteWithChildren,
  GalleryRoute: GalleryRoute,
  HeritageRoute: HeritageRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SculptureIdRoute: SculptureIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
